contact_header: "Dekan"
contact_person: "Prof. Stefan Roth, Ph.D."
contact_room: "S2|02 D103"
contact_street: "Hochschulstraße 10"
contact_postal_code: 64289
contact_city: "Darmstadt"
contact_phone: "+49 6151 16-25500/-25501"
contact_email: "dekanat(a-t)informatik.tu-darmstadt.de"
contact_institutelogo: {url: "https://informatik.tu-darmstadt.de", path: "/assets/img/fb-logo.svg"}

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      menu: [{name: TU Darmstadt, url: www.tu-darmstadt.de}, {name: Test2, url: www.example.com}, {name: Test, url: www.example.com}]
      breadcrumbs: [{name: TU Darmstadt, url: www.tu-darmstadt.de}, {name: Informatik, url: www.informatik.tu-darmstadt.de}]
      sidenav: {mainname: Fachbereich Informatik, mainurl: 'https://www.informatik.tu-darmstadt.de'}
      footer: [{name: Impressum, url: 'https://www.informatik.tu-darmstadt.de/index.php?id=1894'}]
      language: {language: english, url: en}
